#端口号
server:
  port: 8082

dubbo:
  application:
    id: dubbo-provider
    name: dubbo-provider  #应用名称
    owner: aggerChen      #应用所属者
    organization: agger   #应用所属组织
  registry:
    #id: zookeeper-registry #注册中心id
    #protocol: zookeeper    #注册中心协议
    #address: zookeeper://127.0.0.1:2181 #注册中心地址
    #metadata-report:
    #address: zookeeper://127.0.0.1:2181
    address: N/A

  protocol:
    name: dubbo   #协议名称
    port: 20880   #协议端口
    accesslog: dubbo-access.log #协议访问log
  provider:
    retries: 0    #重试次数
    timeout: 3000 #超时时间
  monitor:
    protocol: registry # 注册监控中心
#数据源
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.qq.com
    username: 2842039147@qq.com
    password: gujauqskjlwcdccb
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///yue
    password: root
    username: root

#sql日志
mybatis-plus:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl
    #指定mapper.xml
  mapper-locations: classpath:mapper/*.xml
